# Generated by Django 5.2.7 on 2025-12-03 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anoFundacion', models.PositiveIntegerField()),
                ('propietario', models.CharField(max_length=20)),
                ('foto', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
            },
        ),
        migrations.CreateModel(
            name='SuperHeroe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('poderes', models.CharField(max_length=100)),
                ('Fnacimiento', models.PositiveIntegerField()),
                ('foto', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Superhéroe',
                'verbose_name_plural': 'Superhéroes',
            },
        ),
        migrations.CreateModel(
            name='GrupoDeSuperHeroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('Editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorialGrupo', to='WikiApp.editorial')),
                ('SuperHeroe', models.ManyToManyField(related_name='superheroeGrupo', to='WikiApp.superheroe')),
            ],
            options={
                'verbose_name': 'Grupo de Superheroes',
                'verbose_name_plural': 'Grupos de Superheroes',
            },
        ),
    ]
