# Generated by Django 5.2.7 on 2025-12-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorial',
            options={},
        ),
        migrations.AlterModelOptions(
            name='grupodesuperheroes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='superheroe',
            options={},
        ),
        migrations.RenameField(
            model_name='superheroe',
            old_name='foto',
            new_name='imagenSuperHeroe',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='foto',
        ),
        migrations.AddField(
            model_name='editorial',
            name='imagenEditorial',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='propietario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='superheroe',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
